import { useState } from 'react';
import { Globe2, Clock3, RefreshCw } from 'lucide-react';
import { useTerminal } from '../stores/terminal';
import { useClock } from '../hooks/useClock';
import { countdown, marketSession, sessionDefinitions, wib } from '../lib/sessions';
import { EmptyState, SectionHeading } from '../components/ui/Primitives';

export function Intelligence() {
  const now = useClock(); const calendar = useTerminal(s => s.calendar);
  const error = useTerminal(s => s.calendarError || s.connectionError); const refresh = useTerminal(s => s.refresh);
  const newsWindow = useTerminal(s => s.newsWindow); const setPreferences = useTerminal(s => s.setPreferences);
  const [impact, setImpact] = useState('All events'); const [expanded, setExpanded] = useState<string | null>(null);
  const [showPast, setShowPast] = useState(false);
  const events = calendar?.events.filter(e => (impact === 'All events' || impact.startsWith(e.impact)) && (showPast || new Date(e.at).getTime() >= now)) || [];
  return <><div className="page-heading"><div><div className="eyebrow">CONNECT THE DOTS</div><h1>The world behind the numbers<span className="coral">.</span></h1><p>Macro intelligence, in your time zone.</p></div><div className="clock-badge"><Clock3 size={19} /><strong>{wib(now, true)}</strong><small>WIB · UTC+7</small></div></div>
    <div className="session-grid">{sessionDefinitions.map(def => { const s = marketSession(def, now); return <section className={`session-card ${s.active ? 'dark-card' : 'surface-card'}`} key={s.city}><div><Globe2 size={22} /><span className={s.active ? 'session-open' : 'muted'}>{s.active ? 'OPEN' : s.weekend ? 'WEEKEND' : 'CLOSED'}</span></div><h2>{s.city}</h2><p>{s.zone}</p><span className="session-hours">{wib(s.open)} – {wib(s.close)} WIB</span><small className="session-countdown">{s.active ? 'Closes' : 'Opens'} in {countdown(s.nextChange - now)}</small></section>; })}</div>
    <p className="muted small session-note">Jam sesi mengikuti zona waktu lokal dan daylight saving. Hari libur bursa khusus tidak termasuk.</p>
    <div className="workspace-grid"><section className="surface-card"><SectionHeading title="Economic calendar" /><div className="calendar-feed-status"><span className="outline-badge">{calendar?.source === 'bridge' ? 'Provider calendar' : 'Demo schedule'} · {error ? 'Cached' : 'Connected'}</span><button className="icon-button" onClick={() => void refresh()} aria-label="Refresh calendar"><RefreshCw size={16} /></button></div>
      {calendar?.source === 'demo' && <p className="muted small">Jadwal simulasi harian untuk menguji countdown dan news lock, bukan tanggal rilis resmi.</p>}
      <div className="filter-pills">{['All events', 'High impact', 'Medium impact', 'Low impact'].map(f => <button className={impact === f ? 'active' : ''} key={f} onClick={() => setImpact(f)}>{f}</button>)}</div><label className="checkbox-label"><input type="checkbox" checked={showPast} onChange={e => setShowPast(e.target.checked)} />Show released events</label>
      {error && <p className="form-error" role="status">{error}</p>}
      {events.map(event => <div className="economic-event" key={event.id}><button onClick={() => setExpanded(expanded === event.id ? null : event.id)} aria-expanded={expanded === event.id}><span className="economic-time">{wib(event.at)}<small>{new Date(event.at).toLocaleDateString('en-GB', { timeZone: 'Asia/Jakarta', day: '2-digit', month: 'short' })}</small></span><span className="country-icon">{event.country}</span><span className="economic-title"><strong>{event.title}</strong><small>{event.currency} · <span className="countdown-text">{countdown(new Date(event.at).getTime() - now)}</span></small></span><span className={`impact-badge ${event.impact !== 'High' ? 'neutral' : ''}`}>{event.impact}</span></button>{expanded === event.id && <div className="event-details"><span>Forecast<b>{event.forecast || '—'}</b></span><span>Previous<b>{event.previous || '—'}</b></span><span>Actual<b>{event.actual || 'Pending'}</b></span></div>}</div>)}
      {!events.length && <EmptyState title="No events in this view" text="Ubah filter atau tampilkan jadwal yang telah berlalu." />}
    </section><aside className="right-column"><section className="insight-card macro-insight"><Globe2 size={25} /><div className="overline">NEWS AWARENESS</div><h2>Context before<br />conviction.</h2><p>CPI, PPI, dan NFP dapat mengubah volatilitas. Countdown membantu Anda memahami waktu sebelum menentukan posisi.</p></section><section className="surface-card"><SectionHeading title="News lock preferences" /><p className="muted small">Tampilkan peringatan di chart untuk berita High Impact terkait instrumen aktif.</p><label className="field-label">Warning window<select aria-label="News lock window" value={newsWindow} onChange={e => setPreferences({ newsWindow: Number(e.target.value) })}><option value={30}>30 minutes before release</option><option value={45}>45 minutes before release</option><option value={60}>60 minutes before release</option></select></label><p className="muted small">Peringatan bersifat visual; tidak mengirim atau memblokir order broker.</p></section></aside></div></>;
}
