import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Download, BookOpen, Check } from 'lucide-react';
import { EquityChart } from '../components/charts/EquityChart';
import { SectionHeading } from '../components/ui/Primitives';
import { Modal } from '../components/ui/Modal';
import { TransactionList } from '../components/transactions/TransactionList';
import { useLocalStorage } from '../hooks/useLocalStorage';
import { useTerminal } from '../stores/terminal';
import { dateKey, signedMoney, money } from '../lib/format';
import { isTrade, journalDate, journalMetrics } from '../lib/journal';
import type { Transaction } from '../types';

export function Journal({ transactions, onSelect, notify, initialEquity = 10000 }: { transactions: Transaction[]; onSelect: (t: Transaction) => void; notify: (text: string) => void; initialEquity?: number }) {
  const accountMode = useTerminal(s => s.accountMode);
  const [month, setMonth] = useState(() => { const newest = transactions[0] ? new Date(transactions[0].date) : new Date(); return new Date(newest.getFullYear(), newest.getMonth(), 1); });
  const [selected, setSelected] = useState<string | null>(null); const [detail, setDetail] = useState<string | null>(null);
  const [filter, setFilter] = useState('All activity');
  const [reflections, setReflections, storageError] = useLocalStorage<Record<string, string>>('monetasens.reflections', {});
  const [note, setNote] = useState<string | null>(null); const [saved, setSaved] = useState(false);
  const monthKey = dateKey(month).slice(0, 7); const key = monthKey; // Always use monthKey for persistence across page reloads
  const monthly = useMemo(() => transactions.filter(t => journalDate(t.date).startsWith(monthKey)), [transactions, monthKey]);
  const openingEquity = initialEquity + transactions.filter(t => journalDate(t.date) < `${monthKey}-01`).reduce((sum, t) => sum + t.amount, 0);
  const metrics = journalMetrics(monthly, openingEquity);
  const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(), offset = (month.getDay() + 6) % 7;
  function dayData(day: string) { return monthly.filter(t => journalDate(t.date) === day); }
  function dayMetrics(day: string) { const opening = openingEquity + monthly.filter(t => journalDate(t.date) < day).reduce((sum, t) => sum + t.amount, 0); return journalMetrics(dayData(day), opening); }
  function changeMonth(amount: number) { setMonth(new Date(month.getFullYear(), month.getMonth() + amount, 1)); setSelected(null); setNote(null); setSaved(false); }
  function exportCSV() {
    const escape = (v: string) => `"${(/^[=+@\-\t\r]/.test(v) ? `'${v}` : v).replace(/"/g, '""')}"`;
    const csv = ['Date,Instrument,Type,Net Amount,Fees,Risk Amount,Source,Note', ...monthly.map(t => [escape(t.date), escape(t.name), escape(t.kind), t.amount, t.fees ?? '', t.riskAmount ?? '', escape(t.source || 'local'), escape(t.note)].join(','))].join('\r\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' }));
    const a = document.createElement('a'); a.href = url; a.download = `monetasens-journal-${monthKey}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify('Jurnal berhasil diekspor.');
  }
  const visible = monthly.filter(t => (!selected || journalDate(t.date) === selected) && (filter === 'All activity' || (filter === 'Profits' ? t.kind === 'profit' : filter === 'Losses' ? t.kind === 'loss' : !isTrade(t))));
  const equityData = useMemo(() => { let value = openingEquity; return [{ label: 'Start', value }, ...[...monthly].sort((a, b) => a.date.localeCompare(b.date)).map(t => { value += t.amount; return { label: journalDate(t.date).slice(8), value }; })]; }, [monthly, openingEquity]);
  return <><div className="page-heading"><div><div className="eyebrow">PROGRESS, ONE TRADE AT A TIME</div><h1>Your trading story<span className="coral">.</span></h1><p>{accountMode === 'broker' ? 'Automatically synced broker deals. Net of fees.' : 'Reflect on the process. Grow with every trade.'}</p></div><button className="secondary-button" onClick={exportCSV}><Download size={16} />Export journal</button></div>
    <div className="journal-summary extended"><div className="dark-card"><span className="overline">REALIZED P&L · {month.toLocaleDateString('en-US', { month: 'long' })}</span><h2 className="large-number">{signedMoney(metrics.net)}</h2><span className="muted small">{metrics.trades} trades · {metrics.percent !== null ? `${metrics.percent >= 0 ? '+' : ''}${metrics.percent.toFixed(2)}%` : '—'} on opening equity</span></div><div className="surface-card"><span className="muted">Win rate</span><strong>{metrics.winRate.toFixed(1)}<small>%</small></strong><span className="positive small">{metrics.wins} of {metrics.trades} trades</span></div><div className="surface-card"><span className="muted">Avg realized R</span><strong>{metrics.avgRR?.toFixed(2) ?? '—'}<small>R</small></strong><span className="muted small">Risk known: {metrics.rrCoverage}/{metrics.trades} trades</span></div><div className="surface-card"><span className="muted">Max drawdown</span><strong>{metrics.maxDrawdownPercent.toFixed(2)}<small>%</small></strong><span className="negative small">{money(metrics.maxDrawdown)} peak-to-trough</span></div></div>
    <div className="workspace-grid"><div className="main-column"><section className="surface-card calendar-card"><div className="section-heading"><h2>{month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</h2><div className="calendar-controls"><button className="icon-button" aria-label="Bulan sebelumnya" onClick={() => changeMonth(-1)}><ChevronLeft size={18} /></button><button className="icon-button" aria-label="Bulan berikutnya" onClick={() => changeMonth(1)}><ChevronRight size={18} /></button></div></div><div className="calendar-grid">{['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'].map(d => <span className="calendar-day-label" key={d}>{d}</span>)}{Array.from({ length: offset }, (_, i) => <div key={`blank-${i}`} />)}{Array.from({ length: days }, (_, i) => { const day = dateKey(new Date(month.getFullYear(), month.getMonth(), i + 1)); const m = dayMetrics(day); return <button className={`calendar-cell ${m.net > 0 ? 'win' : m.net < 0 ? 'loss' : ''} ${selected === day ? 'selected' : ''}`} key={day} onClick={() => { setSelected(day); setDetail(day); setNote(null); setSaved(false); }} aria-label={`${day}, ${m.trades} trades`} aria-pressed={selected === day}><span>{i + 1}</span>{m.trades > 0 && <><b>{m.net >= 0 ? '+' : '−'}${Math.abs(m.net).toFixed(0)}</b><small>{m.percent === null ? '—' : `${m.percent >= 0 ? '+' : ''}${m.percent.toFixed(1)}%`}</small></>}</button>; })}</div><div className="calendar-legend"><span><i className="legend-dot green-bg" />Profit</span><span><i className="legend-dot coral-bg" />Loss</span><span>Gray: no trade / breakeven · WIB</span></div></section>
      <section className="activity-section"><div className="section-heading"><h2>{selected || 'Monthly activity'}</h2><select aria-label="Filter transaksi" value={filter} onChange={e => setFilter(e.target.value)}>{['All activity', 'Profits', 'Losses', 'Transfers'].map(f => <option key={f}>{f}</option>)}</select></div>{selected && <button className="text-button" onClick={() => { setSelected(null); setNote(null); }}>Show full month</button>}<TransactionList transactions={visible} onSelect={onSelect} /></section></div>
    <aside className="right-column"><section className="dark-card journal-chart"><SectionHeading title="Cumulative equity" /><p className="muted small">Recorded transactions · opening {money(openingEquity)}</p><EquityChart compact customData={equityData} /></section><section className="surface-card"><div className="section-heading"><h2>A moment to reflect</h2><BookOpen size={20} /></div><p className="muted small">What worked? What would you do differently?</p><label className="field-label" htmlFor="reflection">Reflection · {selected || monthKey}</label><textarea id="reflection" rows={6} placeholder="Today, I learned that..." value={note ?? reflections[key] ?? reflections[selected || monthKey] ?? ''} onChange={e => { const v = e.target.value; setNote(v); setSaved(false); setReflections({ ...reflections, [key]: v }); }} /><button className="primary-button full-width" onClick={() => { setSaved(true); }} disabled={saved}>{saved ? <><Check size={16} />Saved</> : 'Save reflection'}</button>{storageError && <p className="negative small">Catatan hanya tersimpan selama sesi ini.</p>}</section><p className="muted small">Avg R = net PnL ÷ initial risk. Trade tanpa data risk tidak dimasukkan. Drawdown dihitung dari closed-trade equity, tanpa floating PnL.</p></aside></div>
    {detail && <Modal title={`Daily audit · ${detail}`} onClose={() => setDetail(null)}><div className="confirmation-amount"><small>Net realized P&L</small><strong className={dayMetrics(detail).net >= 0 ? 'positive' : 'negative'}>{signedMoney(dayMetrics(detail).net)}</strong></div><div className="detail-rows"><span>Closed trades<b>{dayMetrics(detail).trades}</b></span><span>Daily return<b>{dayMetrics(detail).percent?.toFixed(2) ?? '—'}%</b></span><span>Source<b>{accountMode === 'broker' ? 'Broker auto-sync' : 'Local journal'}</b></span></div><TransactionList transactions={dayData(detail)} onSelect={t => { setDetail(null); onSelect(t); }} /></Modal>}
  </>;
}
